platform :ios, ‘7.0’
pod 'AFNetworking'
#pod 'ASIHTTPRequest'
pod 'ReactiveCocoa'
#pod 'ProtocolBuffers'
pod 'pop'
#pod 'Mantle'
pod 'RESideMenu'
pod 'SDWebImage'
pod 'MBProgressHUD'
#pod 'FlatUIKit'
pod 'SVProgressHUD'
#pod 'JSQMessagesViewController'
pod 'CocoaLumberjack'
#pod 'AsyncDisplayKit'
#pod 'Shimmer'
#pod 'iCarousel'
#pod 'RestKit'
#pod 'GPUImage'
#pod 'PNChart'
#pod 'SWTableViewCell'
#pod 'TTTAttributedLabel'
#pod 'BlocksKit'
#pod 'AwesomeMenu'
#pod 'MWPhotoBrowser'
pod 'MJRefresh'
#pod 'IQKeyboardManager'
#pod 'NSLogger'
pod 'FLAnimatedImage'
#pod 'iRate'
pod 'SIAlertView'
#pod 'Colours'
#pod 'FXBlurView'
pod 'Masonry'
#pod 'FastImageCache', '~> 1.3'
#pod 'SSToolkit', '~> 2.0.0'
#pod 'MMXXMPPFramework', '~> 3.6.13'
pod 'PSCollectionView', '~> 0.0.1'
pod 'Bugly'
pod 'ReactiveViewModel', '~> 0.3'
pod 'REMenu'
#pod 'KxMenu'
pod 'LMDropdownView'
pod 'WebViewJavascriptBridge'
#pod 'mailcore2-ios'
pod 'Google-Mobile-Ads-SDK'
pod 'BIZGrid4plus1CollectionViewLayout'
pod 'NHBalancedFlowLayout'
pod 'CCHexagonFlowLayout'
pod 'HMSegmentedControl'
pod 'COSTouchVisualizer'
pod 'SCLAlertView-Objective-C'
pod 'ZFDragableModalTransition'
#pod 'UMengSocial'
pod 'jot'
pod 'FaceAwareFill'
pod 'NKOColorPickerView'
pod 'CMPopTipView'
pod 'iRate'
pod 'JDStatusBarNotification'
pod 'WebViewJavascriptBridge'
#pod 'ZXingObjC'
#pod 'ZBarSDK'
pod 'TOWebViewController'
pod 'LCActionSheet'
